{% set name = "django_param" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/django-param/{{ name }}-{{ version }}.tar.gz
  sha256: 7cd1c73c993f14bd2ac3ac464f4cd4bd49c75c38c61aa00c082d140f8da8fcf3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyyaml >=5.1,<5.2
    - django-gravatar2 >=1.4,<1.5
    - psycopg2 >=2.8,<2.9
    - param >=1.9,<2.0
    - django >=2.2,<2.3
    - django-select2 >=7.4,<7.5
    - django-colorfield >=0.3,<0.4
    - pandas >=0.25,<0.26

test:
  imports:
    - django_param

about:
  home: https://pypi.org/project/django-param/
  summary: django-axes, ParamForm class which allows python param to be used in django form.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
