{% set name = "django_param" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/django-param/{{ name }}-{{ version }}.tar.gz
  sha256: 7067c2240e72e3e3b2f4be04650163599cb1a08977a41156333bae4f3bfce8a0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyyaml >=5.1,<5.2
    - django-gravatar2 >=1.4,<1.5
    - psycopg2 >=2.8,<2.9
    - param >=1.9,<2.0
    - django >=2.2,<2.3
    - django-select2 >=7.4,<7.5
    - django-colorfield >=0.3,<0.4
    - pandas >=0.25,<0.26

test:
  imports:
    - django_param

about:
  home: https://pypi.org/project/django-param/
  summary: django-axes, ParamForm class which allows python param to be used in django form.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
    - sdc50
    - msbrown47
